export const cityData = [
  { name: '강원', code: 'gangwon' },
  { name: '서울', code:'seoul' },
  { name:'인천', code:'incheon' },
  { name:'경기', code:'gyeonggi' },
  { name:'충남', code:'chungnam' },
  { name:'충북', code:'chungbuk' },
  { name:'경남', code:'gyeongnam' },
  { name:'대구', code:'daegu' },
  { name:'전남', code:'jeonnam' },
  { name:'울산', code:'ulsan' },
  { name:'경북', code:'gyeongbuk' },
  { name:'광주', code:'gwangju' },
  { name:'전북', code:'jeonbuk' },
  { name:'부산', code:'busan' },
  { name:'제주', code:'jeju' },
  { name:'세종', code:'sejong' },
  { name:'대전', code:'daejeon' },
];